name: stroll_test
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  logger: ^1.1.0
  provider: ^6.0.1
  shared_preferences: ^2.0.8
  get_it: ^7.2.0
  flutter_svg: ^0.22.0
  cached_network_image: ^3.2.3
  flutter_hooks: ^0.18.6
  flutter_staggered_animations: ^1.1.1
  hive: ^4.0.0-dev.2
  isar_flutter_libs: ^4.0.0-dev.13
  path_provider: ^2.1.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0



flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/svg/
    - assets/png/
    - assets/png/2.0x/
    - assets/png/1.5x/
    - assets/png/3.0x/



  fonts:
    - family: Proxima
      fonts:
        - asset: assets/fonts/Proxima_Nova_Extrabold.otf
          weight: 800

        - asset: assets/fonts/Proxima_Nova_Alt_Bold.otf
          weight: 700

        - asset: assets/fonts/Proxima_Nova_Semibold.otf
          weight: 600

        - asset: assets/fonts/Proxima_Nova_Regular.otf
          weight: 500

        - asset: assets/fonts/Proxima_Nova_Thin.otf
          weight: 200

        - asset: assets/fonts/Proxima_Nova_Thin_Italic.otf
          weight: 200
          style: italic

